/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carreracarros;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Patricio
 */
public class Pista extends javax.swing.JFrame {

    /**
     * Creates new form Pista
     */
    public Pista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReloj = new javax.swing.JLabel();
        lblCarro1 = new javax.swing.JLabel();
        lblCarro2 = new javax.swing.JLabel();
        lblCarro3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnEmpezar = new javax.swing.JButton();
        posicioncarro3 = new javax.swing.JLabel();
        posicioncarro1 = new javax.swing.JLabel();
        posicioncarro2 = new javax.swing.JLabel();
        lblLlegada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReloj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblReloj.setForeground(new java.awt.Color(51, 0, 153));
        lblReloj.setText("0:0:0");
        getContentPane().add(lblReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        lblCarro1.setBackground(new java.awt.Color(102, 102, 255));
        lblCarro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro-deportivo (1).png"))); // NOI18N
        lblCarro1.setOpaque(true);
        getContentPane().add(lblCarro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 70));

        lblCarro2.setBackground(new java.awt.Color(255, 255, 0));
        lblCarro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro-deportivo.png"))); // NOI18N
        lblCarro2.setOpaque(true);
        getContentPane().add(lblCarro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 70, -1));

        lblCarro3.setBackground(new java.awt.Color(255, 0, 153));
        lblCarro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche-deportivo.png"))); // NOI18N
        lblCarro3.setOpaque(true);
        getContentPane().add(lblCarro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pista-carreras-linea-salida-llegada-fondo-carreras-coches-o-karting-vista-superior_172533-883.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnEmpezar.setText("Empezar");
        getContentPane().add(btnEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        posicioncarro3.setFont(new java.awt.Font("Chalkduster", 0, 24)); // NOI18N
        posicioncarro3.setForeground(new java.awt.Color(0, 0, 0));
        posicioncarro3.setText("Posicion");
        getContentPane().add(posicioncarro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, -1, 70));

        posicioncarro1.setFont(new java.awt.Font("Chalkduster", 0, 24)); // NOI18N
        posicioncarro1.setForeground(new java.awt.Color(0, 0, 0));
        posicioncarro1.setText("Posicion");
        getContentPane().add(posicioncarro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, -1, 70));

        posicioncarro2.setFont(new java.awt.Font("Chalkduster", 0, 24)); // NOI18N
        posicioncarro2.setForeground(new java.awt.Color(0, 0, 0));
        posicioncarro2.setText("Posicion");
        getContentPane().add(posicioncarro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, -1, 70));

        lblLlegada.setBackground(new java.awt.Color(0, 255, 0));
        lblLlegada.setText("LLEGADA");
        lblLlegada.setOpaque(true);
        getContentPane().add(lblLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 100, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblReloj() {
        return lblReloj;
    }

    public void setLblReloj(JLabel lblReloj) {
        this.lblReloj = lblReloj;
    }

    public JButton getBtnEmpezar() {
        return btnEmpezar;
    }

    public void setBtnEmpezar(JButton btnEmpezar) {
        this.btnEmpezar = btnEmpezar;
    }

    public JLabel getLblCarro1() {
        return lblCarro1;
    }

    public void setLblCarro1(JLabel lblCarro1) {
        this.lblCarro1 = lblCarro1;
    }

    public JLabel getLblCarro2() {
        return lblCarro2;
    }

    public void setLblCarro2(JLabel lblCarro2) {
        this.lblCarro2 = lblCarro2;
    }

    public JLabel getLblCarro3() {
        return lblCarro3;
    }

    public void setLblCarro3(JLabel lblCarro3) {
        this.lblCarro3 = lblCarro3;
    }

    public JLabel getLblLlegada() {
        return lblLlegada;
    }

    public void setLblLlegada(JLabel lblLlegada) {
        this.lblLlegada = lblLlegada;
    }

    public JLabel getPosicioncarro1() {
        return posicioncarro1;
    }

    public void setPosicioncarro1(JLabel lblCarro1) {
        this.posicioncarro1 = lblCarro1;
    }

    public JLabel getPosicioncarro2() {
        return posicioncarro2;
    }

    public void setPosicioncarro2(JLabel posicioncarro2) {
        this.posicioncarro2 = posicioncarro2;
    }

    public JLabel getPosicioncarro3() {
        return posicioncarro3;
    }

    public void setPosicioncarro3(JLabel posicioncarro3) {
        this.posicioncarro3 = posicioncarro3;
    }
    
    
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCarro1;
    private javax.swing.JLabel lblCarro2;
    private javax.swing.JLabel lblCarro3;
    private javax.swing.JLabel lblLlegada;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JLabel posicioncarro1;
    private javax.swing.JLabel posicioncarro2;
    private javax.swing.JLabel posicioncarro3;
    // End of variables declaration//GEN-END:variables
}
